version: '3.8'

services:
  agent:
    build: .
    container_name: kindleberry_agent
    network_mode: "host"
    privileged: true # Necessário para acesso direto ao hardware GPIO via Docker
    volumes:
      - /sys:/sys:ro
      - /dev:/dev # Expõe os dispositivos para o rpi-lgpio
    restart: unless-stopped